[metadata]
addr = 0xf0a
size = 0xa0
last_change = 2024-01-20T05:38:38.875861Z

[header]
last_change = 2024-01-20T05:38:38.875861Z
name = "user_input"
addr = 0xf0a
type = "void"

[header.args.0]
offset = 0x0
name = "dst"
type = "char*"
size = 0x8

[header.args.1]
offset = 0x1
name = "len"
type = "int"
size = 0x4
