[metadata]
addr = 0x180e
size = 0x146
last_change = 2024-01-20T08:16:40.868564Z

[header]
last_change = 2024-01-20T08:16:40.868564Z
name = "leak_vuln_here"
addr = 0x180e
type = "long"

[stack_vars.-0x20]
offset = -32
name = "local_20"
type = "char *"
size = 0x8
addr = 0x180e
