[metadata]
addr = 0x180e
size = 0x146
last_change = 2024-01-20T08:52:40.339360Z

[header]
last_change = 2024-01-20T08:52:40.339360Z
name = "add_type"
addr = 0x180e
type = "long"

[stack_vars.-0x20]
offset = -32
name = "local_20"
type = "char *"
size = 0x8
addr = 0x180e
