[metadata]
addr = 0x1fe6
size = 0x2fc
last_change = 2024-01-20T06:52:01.155665Z

[header]
name = "submit_bugreport"
addr = 0x1fe6

[stack_vars.-0x28]
offset = -40
name = "description_len"
type = "ulong"
size = 0x8
addr = 0x1fe6
