[metadata]
addr = 0x1ec9
size = 0x11d
last_change = 2024-01-20T09:02:22.889138Z

[header]
last_change = 2024-01-20T09:02:22.889138Z
name = "remove_bugreport"
addr = 0x1ec9
type = "struct product*"

[header.args.0]
offset = 0x0
name = "product"
type = "struct product*"
size = 0x8

[header.args.1]
offset = 0x1
name = "report"
type = "struct bugreport*"
size = 0x8
