[metadata]
addr = 0x13b3
size = 0x1fe
last_change = 2024-01-20T07:31:19.651910Z

[header]
name = "add_product"
addr = 0x13b3

[stack_vars.-0x58]
offset = -88
name = "buf"
type = "char[64]"
size = 0x40
addr = 0x13b3

[stack_vars.-0x68]
offset = -104
name = "local_68"
type = "int"
size = 0x4
addr = 0x13b3

[stack_vars.-0x64]
offset = -100
name = "index"
type = "int"
size = 0x4
addr = 0x13b3
