[metadata]
addr = 0x30a3
size = 0x14e
last_change = 2024-01-20T08:04:31.435366Z

[header]
last_change = 2024-01-20T08:04:31.435366Z
name = "main"
addr = 0x30a3
type = "int"

[header.args.0]
offset = 0x0
name = "argc"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "argv"
type = "char**"
size = 0x8

[header.args.2]
offset = 0x2
name = "envp"
type = "char**"
size = 0x8
