[metadata]
addr = 0x15b1
size = 0x139
last_change = 2024-01-20T07:14:15.555893Z

[header]
last_change = 2024-01-20T07:14:15.555893Z
name = "sub_15b1"
addr = 0x15b1
type = "char**"

[header.args.0]
offset = 0x0
name = "arg1"
type = "char*"
size = 0x8

[header.args.1]
offset = 0x1
name = "arg2"
type = "int"
size = 0x4
