[metadata]
addr = 0x16eb
size = 0x122
last_change = 2024-01-20T08:55:03.644328Z

[header]
last_change = 2024-01-20T08:55:03.644328Z
name = "sub_16eb"
addr = 0x16eb
type = "long"

[header.args.0]
offset = 0x0
name = "arg1"
type = "char*"
size = 0x8
