[metadata]
addr = 0x15b1
size = 0x13a
last_change = 2024-01-20T08:52:36.575119Z

[header]
last_change = 2024-01-20T08:52:36.575119Z
name = "insert_type"
addr = 0x15b1
type = "struct type*"

[stack_vars.-0x14]
offset = -20
name = "local_14"
type = "int"
size = 0x4
addr = 0x15b1

[stack_vars.-0x18]
offset = -24
name = "local_18"
type = "int"
size = 0x4
addr = 0x15b1

[header.args.0]
offset = 0x0
name = "name"
type = "char*"
size = 0x8

[header.args.1]
offset = 0x1
name = "arg2"
type = "int"
size = 0x4
