[metadata]
addr = 0x13b3
size = 0x1fd
last_change = 2024-01-20T05:57:26.571349Z

[header]
name = "sub_13b3"
addr = 0x13b3
type = "long"

[stack_vars.-0x68]
offset = -104
name = "local_68"
type = "int"
size = 0x4
addr = 0x13b3

[stack_vars.-0x64]
offset = -100
name = "local_64"
type = "int"
size = 0x4
addr = 0x13b3

[stack_vars.-0x58]
offset = -88
name = "local_58"
type = "char[72]"
size = 0x48
addr = 0x13b3
