[metadata]
addr = 0x1ace
size = 0xcc
last_change = 2024-01-20T05:49:27.298368Z

[header]
name = "print_products"
addr = 0x1ace

[stack_vars.-0xc]
offset = -12
name = "i"
type = "uint"
size = 0x4
addr = 0x1ace
