[metadata]
addr = 0xea9
size = 0x60

[header]
name = "read_to_longlong_vuln?"
addr = 0xea9
type = "long"

[stack_vars.-0x38]
offset = -56
name = "buf"
type = "char[40]"
size = 0x28
addr = 0xea9

[stack_vars.-0x10]
offset = -16
name = "canary"
type = "long"
size = 0x8
addr = 0xea9
