[metadata]
addr = 0xea9
size = 0x61
last_change = 2024-01-20T05:26:47.287936Z

[header]
name = "vuln_read"
addr = 0xea9

[stack_vars.-0x38]
offset = -56
name = "buf"
type = "char[40]"
size = 0x28
addr = 0xea9

[stack_vars.-0x10]
offset = -16
name = "canary"
type = "long"
size = 0x8
addr = 0xea9
