[metadata]
addr = 0x1fe6
size = 0x2fc
last_change = 2024-01-20T07:07:07.841090Z

[header]
name = "submit_bugreport"
addr = 0x1fe6
type = "void*"

[stack_vars.-0x28]
offset = -40
name = "description_len"
type = "ulong"
size = 0x8
addr = 0x1fe6
