[metadata]
addr = 0x2aec
size = 0x24a

[header]
name = "admin_userinfo"
addr = 0x2aec

[stack_vars.-0x128]
offset = -296
name = "local_128"
type = "byte[16]"
size = 0x10
addr = 0x2aec

[stack_vars.-0x10]
offset = -16
name = "local_10"
type = "long"
size = 0x8
addr = 0x2aec

[stack_vars.-0x98]
offset = -152
name = "password_hash_hex"
type = "char[136]"
size = 0x88
addr = 0x2aec
