[metadata]
addr = 0x1b9a
size = 0x258
last_change = 2024-01-20T07:54:24.610667Z

[header]
name = "show_vulnerability"
addr = 0x1b9a

[stack_vars.-0x18]
offset = -24
name = "report"
type = "bugreport *"
size = 0x8
addr = 0x1b9a
