[metadata]
addr = 0x1954
size = 0xcc
last_change = 2024-01-20T07:13:44.213396Z

[header]
last_change = 2024-01-20T07:13:44.213396Z
name = "sub_1954"
addr = 0x1954
type = "long"

[stack_vars.-0xc]
last_change = 2024-01-20T07:12:09.007537Z
offset = -12
name = "i"
type = "int"
size = 0x0
addr = 0x1954

[header.args.0]
offset = 0x0
name = "arg1"
type = "long"
size = 0x8
